name: Node.js CI2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g pnpm@6
    - uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store
    - run: sudo apt-get install libocct-data-exchange-dev libocct-modeling-data-dev 
    - run: npm install -g pnpm@6
    - run: pnpm recursive install
    - run: pnpm run build
    - run: pnpm run pretest
    - run: pnpm test
